characters = [
    "Goku (Z-Early)",
    "Goku (Z-Mid)",
    "Goku (Z-Mid) Super Saiyan",
    "Goku (Z-End)",
    "Goku (Z-End) Super Saiyan",
    "Goku (Z-End) Super Saiyan 2",
    "Goku (Z-End) Super Saiyan 3",
    "Goku (Super)",
    "Goku (Super) Super Saiyan",
    "Goku (Super) Super Saiyan God",
    "Goku (Super) Super Saiyan God Super Saiyan",
    "Vegeta (Z-Scouter)",
    "Great Ape Vegeta",
    "Vegeta (Z-Early)",
    "Vegeta (Z-Early) Super Saiyan",
    "Super Vegeta",
    "Vegeta (Z-End)",
    "Vegeta (Z-End) Super Saiyan",
    "Vegeta (Z-End) Super Saiyan 2",
    "Majin Vegeta",
    "Vegeta (Super)",
    "Vegeta (Super) Super Saiyan",
    "Vegeta (Super) Super Saiyan God",
    "Vegeta (Super) Super Saiyan God Super Saiyan",
    "Piccolo",
    "Krillin",
    "Yamcha",
    "Tien",
    "Trunks (Melee) Super Saiyan",
    "Future Trunks Super Saiyan",
    "Frieza (Super)",
    "Cell Perfect Form",
    "Majin Buu",
    "Mr. Satan",
    "Android 17 (Super)",
    "Android 18",
    "Broly (Super)",
    "Broly (Super) Super Saiyan",
    "Jiren",
    "Bergamo",
    "Super Trunks",
    "Dyspo",
    "Kakunsa",
    "Master Roshi Max Power",
    "Nappa",
    "Burter",
    "Toppo",
    "Jeice",
    "Kale Super Saiyan (Berserk)",
    "Broly (Super) Super Saiyan Full Power",
    "Hit",
    "Beerus",
    "Gohan (Adult)",
    "Videl",
    "Gohan (Future)",
    "Gohan (Future) Super Saiyan",
    "Gohan (Kid)",
    "Master Roshi",
    "Trunks (Sword)",
    "Trunks (Sword) Super Saiyan",
    "Whis",
    "Trunks (Kid)",
    "Trunks (Kid) Super Saiyan",
    "Goten",
    "Goten Super Saiyan",
    "Gotenks",
    "Gotenks Super Saiyan",
    "Gotenks Super Saiyan 3",
    "Kale",
    "DRAGON BALL Sparking! ZERO, Kale",
    "Kale Super Saiyan",
    "Caulifla",
    "Caulifla Super Saiyan 2",
    "Kefla",
    "Kefla Super Saiyan",
    "Kefla Super Saiyan 2",
    "Vegito",
    "Vegito Super Saiyan God Super Saiyan",
    "Gogeta (Super)",
    "Gogeta (Super) Super Saiyan",
    "Gogeta (Super) Super Saiyan God Super Saiyan",
    "Fused Zamasu",
    "Fused Zamasu Half-Corrupted",
    "Goku (Super) Ultra Instinct",
    "Gohan (Adult) Super Saiyan 2",
    "Golden Frieza",
    "Bardock",
    "Raditz",
    "Goku Black",
    "Zamasu",
    "Jiren Full Power",
    "Goku (Super) Ultra Instinct -Sign-",
    "Super Vegito",
    "Yajirobe",
    "Dabura",
    "Spopovich",
    "Goku Black Super Saiyan Rosé",
    "Future Trunks",
    "Ribrianne",
    "Roasie",
    "Anilaza",
    "Nail",
    "DRAGON BALL: Sparking! ZERO Nail",
    "Frieza (Z) 1st Form",
    "Frieza (Z) 2nd Form",
    "Frieza (Z) 3rd Form",
    "Frieza (Z) 4th Form",
    "Frieza (Z) Full Power",
    "Chiaotzu",
    "Saibaman",
    "Zarbon",
    "Super Zarbon",
    "Dodoria",
    "Cui",
    "Ginyu",
    "Captain Ginyu",
    "Recoome",
    "Guldo",
    "Gohan (Teen)",
    "Gohan (Teen) Super Saiyan",
    "Gohan (Teen) Super Saiyan 2",
    "Trunks (Melee)",
    "Android 17 (Z)",
    "Android 17",
    "Android 16",
    "Android 19",
    "Dr. Gero",
    "Cell 1st Form",
    "Cell 2nd Form",
    "Perfect Cell",
    "Cell Jr.",
    "Piccolo (Fused with Kami)",
    "King Cold",
    "Mecha Frieza",
    "Great Saiyaman",
    "Babidi",
    "Gohan (Adult) Super Saiyan",
    "Majin Buu (Evil)",
    "Evil Buu",
    "Super Buu",
    "Ultimate Gohan",
    "Super Buu (Gotenks Absorbed)",
    "Super Buu (Gohan Absorbed)",
    "Kid Buu",
    "Goku (GT)",
    "Pan (GT)",
    "Goku (GT) Super Saiyan",
    "Baby Vegeta (GT)",
    "Goku (GT) Super Saiyan 3",
    "Super Baby 1 (GT)",
    "Super Baby 1",
    "Super Baby 2 (GT)",
    "Uub (GT)",
    "Majuub (GT)",
    "Goku (GT) Super Saiyan 4",
    "Great Ape Baby (GT)",
    "Syn Shenron",
    "Syn Shenron (GT)",
    "Omega Shenron (GT)",
    "Vegeta (GT) Super Saiyan 4",
    "Gogeta (GT) Super Saiyan 4",
    "Frieza Force Soldier",
    "Cabba",
    "Frost",
    "Toppo, God of Destruction",
    "Cabba Super Saiyan",
    "Cabba Super Saiyan 2",
    "Broly (Z)",
    "Broly (Z) Super Saiyan",
    "Broly (Z) Legendary Super Saiyan",
    "Cooler",
    "Cooler Final Form",
    "Metal Cooler",
    "Android 13",
    "Fusion Android 13",
    "Super Garlic Jr.",
    "Dr. Wheelo",
    "Lord Slug",
    "Lord Slug Giant Form",
    "Turles",
    "Bojack",
    "Full-Power Bojack",
    "Hirudegarn",
    "Tapion",
    "Janemba",
    "Super Janemba",
    "Super Gogeta (Z)",
    "Goku (Teen)"
]
